name: Publish VSCode Extension

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Build Extension
        run: npm run compile

      - name: Build package
        run: vsce package

      - name: Publish to Marketplace
        run: |
          vsce publish --pat "$VSCE_TOKEN" -i "defang-${{ github.ref_name }}.vsix"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: defang-${{ github.ref_name }}.vsix
          path: defang-${{ github.ref_name }}.vsix
